# jwt configuration
jwt:
  signing-key: 'wwengg'
  expires-time: 604800
  buffer-time: 86400

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[pigeon]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

rpcx:
  base-path: 'rpcx'
  addr: '127.0.0.1:8889'
  network: 'tcp'
  register: "etcdv3"

etcd-v3:
  addr:
    - "127.0.0.1:23791"
    - "127.0.0.1:23792"
    - "127.0.0.1:23793"

redis:
  addr: ["127.0.0.1:6379"]
  db: 0

tcp-config:
  name: "pigeon"
  ip: "0.0.0.0"
  tcp-port: 8999
  max-conn: 200
  worker-pool-size: 50
  max-worker-task-len: 1024
  max-msg-chan-len: 1024
  max-packet-size: 4096

websocket:
  enable: true
  addr: "127.0.0.1:8998"
  conn-write-timeout: 30
  conn-read-timeout: 30
  max-header-len: 4096
